### ISSUE TITLE
list페이지 최신순정렬 list서버<->클라이언트 전송

### ISSUE THREAD

**Issue by Daljakim** [JEONGSOOYEON/subwaytoday#3]
list페이지 최신순정렬 조합list 서버<->클라이언트 전송
GET방식으로 서버에서 클라이언트로 보낼거예요~

**Comment by JEONGSOOYEON** [comment]
> 오늘 중으로 마무리 될 예정입니다. 급하시면 emergency 외쳐주세요^^ @hjjin104

emergency!!🚨

**Comment by Daljakim** [comment]
앗! 네 지금 바로 완료했고 푸시하겠습니다. 확인부탁드려요~~  @JEONGSOOYEON

**Comment by JEONGSOOYEON** [comment]
> 앗! 네 지금 바로 완료했고 푸시하겠습니다. 확인부탁드려요~~ @JEONGSOOYEON

확인했습니다! close 하시면 될 거 같아요~
